In [27]:
import sklearn
import numpy as np
import pandas as pd
import os

In [5]:
gears_category = os.listdir('output_challenge2')
gears_category.remove('.ipynb_checkpoints')

In [22]:
target_array = []
images_array = []

for category in gears_category:
    print(category)
    for item in os.listdir('output_challenge2/' + category):
        target_array.append(category)
        array = np.fromfile('/'.join(['output_challenge2', category, item]), dtype='uint8')
        array_flat = array.flatten()
        images_array.append(array_flat)

harnesses_transformed
tents_transformed
gloves_transformed
hardshell_jackets_transformed
pulleys_transformed
carabiners_transformed
boots_transformed
rope_transformed
helmets_transformed
axes_transformed
insulated_jackets_transformed
crampons_transformed


In [25]:
images_array[0].shape, 128*128*3

((49152,), 49152)

In [61]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(np.array(images_array), target_array, )

In [62]:
X_train.shape, X_val.shape, len(y_train), len(y_val)

((1591, 49152), (531, 49152), 1591, 531)

In [63]:
from collections import Counter
awesome_array = np.array(list(Counter(y_val).values()))/np.sum(list(Counter(y_val).values())) - np.array(list(Counter(y_train).values()))/np.sum(list(Counter(y_train).values()))

assert(np.max(awesome_array)<0.05)

In [67]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()

knn.fit(X_train, y_train)

prediction = knn.predict(X_val)

In [68]:
from sklearn.metrics import confusion_matrix, accuracy_score

print(confusion_matrix(y_val, prediction))

print(accuracy_score(y_val, prediction))

[[ 21   0   0   2   0   0   0   0   0   0   0   0]
 [  0  27   0   0   0   0   0   0   0   0   0   0]
 [  0   1  59   0   0   0   0   0   0   0   2   3]
 [  0   1   0  24   0   0   0   0   1   0   0   5]
 [  0   0   0   0  54   3   0   0   0   0   2   0]
 [  0   0   0   0   0 101   0   0  13   0   0   0]
 [  0   0   0   0   2   1  42   0   0   0   2   1]
 [  0   0   0   0   0   0   0  18   2   0   0   0]
 [  0   1   0   0   1  24   0   0  29   0   0   0]
 [  0   0   0   0   0   2   0   0   1   3   0   3]
 [  0   0   0   1   3   2   0   0   1   1  39   1]
 [  0   0   0   0   0   1   0   0   0   0   0  31]]
0.8436911487758946
